# Generated by Django 4.1.7 on 2023-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品名')),
                ('detail', models.TextField(max_length=1000, verbose_name='商品詳細')),
                ('price', models.PositiveIntegerField(verbose_name='商品金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='担当者名')),
                ('email', models.EmailField(max_length=256, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=32, verbose_name='電話番号')),
            ],
        ),
    ]
